#### Building Docker Image ####
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/myapp:$SHORT_SHA', '-t', 'asia-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/myapp:${_IMAGE_TAG}', '.' ]

#### Pushing Docker Image ####
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: /bin/sh
  args: 
  - -c
  - |
    docker push asia-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/myapp:$SHORT_SHA
    docker push asia-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/myapp:${_IMAGE_TAG}

# This step generates the new manifest
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  secretEnv: ['GIT_ACCESS_TOKEN']
  args:
  - '-c'
  - |
    git clone https://pranavdhopey:$$GIT_ACCESS_TOKEN@github.com/pranavdhopey/myapp-deployment.git -b ${_CD_BRANCH}
    echo "Updating image tag version ..."
    cd myapp-deployment
    sed "s/GOOGLE_CLOUD_PROJECT/$PROJECT_ID/g" deployment.yaml.tpl | \
    sed "s/COMMIT_SHA/${SHORT_SHA}/g" > deployment.yaml
    echo "Pushing changes to k8s manifest repo ..."
    git config --global user.name "pranav dhopey"
    git config --global user.email "pranav.dhope@gmail.com"
    git add -A
    git commit -m "[Cloud Builder] Updated image tag asia-docker.pkg.dev/$PROJECT_ID/${_ARTIFACT_REPO}/myapp:$SHORT_SHA from commit ${COMMIT_SHA}"
    git push https://pranavdhopey:$$GIT_ACCESS_TOKEN@github.com/<your-github-id>/myapp-deployment.git ${_CD_BRANCH}
    
availableSecrets:
  secretManager:
  - versionName: projects/$PROJECT_NUMBER/secrets/github-access-token/versions/latest
    env: 'GIT_ACCESS_TOKEN'

# options:
#   logging: CLOUD_LOGGING_ONLY
